# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        # Incluir archivos necesarios
        ('generator_cartones.py', '.'),
        ('views/generator_cartones.py', 'views'),
        ('views/*.py', 'views'),
        ('models/*.py', 'models'),
        ('utils/*.py', 'utils'),
        # Incluir hooks de PIL
        ('hooks', 'hooks'),
    ],
    hiddenimports=[
        'numpy',
        'pandas',
        'matplotlib',
        'openpyxl',
        'scipy',
        'PIL',
        'PIL._imaging',
        'PIL.Image',
        'PIL.ImageDraw', 
        'PIL.ImageFont',
        'PIL.ImageOps',
        'PIL.ImageFilter',
        'PIL.ImageChops',
        'tkinter',
        'tkinter.ttk',
        'pathlib',
        'datetime',
        'json',
        'threading',
        'tempfile',
        'webbrowser',
        'os',
        'sys',
        'time',
        # Para matplotlib
        'matplotlib.backends.backend_agg',
        'matplotlib.backends.backend_tkagg',
        'matplotlib.pyplot',
        'matplotlib.backends.backend_pdf',
    ],
    hookspath=['hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='SistemaGestionTablas',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)